### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ajansel** [laujonat/clickr#4]
# Routes

- [ ] API endpoint routes accurately reflect MVPs and Component Hierarchy
  - What is the session dashboard? Do you mean search maybe? 
  - `Get single user information` should read: `Get single user's information`
  - You don't need the following route because you should just use the photo show route: 
```
GET /api/albums/:id/photos/:id
Retrieve photo from album
```
  - The only nested route that you'll need for comments or tags is the `create` route because all the others we will already have the actual idea of the comment / tag. 
  - We should discuss how you anticipate tags being used (we can discuss tomorrow in person). 
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
  - You will likely need a `/feed` or `/dashboard` frontend route 
  - You should also add an album and photo show frontend route
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
  - Add your static pages route and you should be in good shape 
- [x] Each route has a description
  - General feedback: You need to indent your bullet description underneath the route or use a `-` after the route and have the description after it. There are too many same-level bullets right now and it makes it difficult to read. 
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
  - You can't have multiple `:id`s within the API endpoint routes, you'll need one of them to be `:photo_id` for exmaple
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

# Comments:
Once you complete the above, comment on the issue and then I will review it and close it!

**Comment by laujonat** [comment]
Because comments belong to a photo, wouldn't this still be necessary? 
`GET /api/photos/:id/comments `
My thought was that retrieving all comments would be a little pointless in this case. 


So as far as front end routes go, I've noticed something from the website. All photos belong to a user, so every :SHOW of a photo would have a url with a username nested in the url. Maybe I'm lacking some concepts in React Router, but what is the correct way of implementing this? Because I will be included a wildcard :id for photos, comments, and tags, wouldn't I be setting this up in Router? 

I've addressed the issues listed above. Please let me know if I have missed something. Thank you.

**Comment by ajansel** [comment]
We can discuss this in more detail during our 1-on-1 as well before closing this!

**Comment by ajansel** [comment]
Good to go, good work!
